<?php
/**
 * OrdersApiTest
 * PHP version 5
 *
 * @category Class
 * @package  EzzeSiftuz\OrdersV3
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Orders
 *
 * This API documentation describes all endpoints for orders - version 3
 *
 * OpenAPI spec version: v3
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.20
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace EzzeSiftuz\OrdersV3;

use EzzeSiftuz\OrdersV3\Configuration;
use EzzeSiftuz\OrdersV3\ApiException;
use EzzeSiftuz\OrdersV3\ObjectSerializer;

/**
 * OrdersApiTest Class Doc Comment
 *
 * @category Class
 * @package  EzzeSiftuz\OrdersV3
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class OrdersApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for cancelPartnerOrders
     *
     * Cancel all PositionItems of an order.
     *
     */
    public function testCancelPartnerOrders()
    {
    }

    /**
     * Test case for findPartnerOrders
     *
     * Get a list of orders which can be filtered on fulfillmentStatus..
     *
     */
    public function testFindPartnerOrders()
    {
    }

    /**
     * Test case for getPartnerOrderBySalesOrderId
     *
     * Get a single order via Sales Order Id.
     *
     */
    public function testGetPartnerOrderBySalesOrderId()
    {
    }
}
